version: '2'
services:
  jenkins:
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
volumes:
  jenkins_data:
    driver: local
