name: CI

on:
  - push

jobs:
  tests:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Test
        run: ./gradlew test
